INSERT INTO dbo.Team (City, Name, Shorthand)
VALUES ('Buffalo', 'Bills', 'BUF')
    , ('Miami', 'Dolphins', 'MIA')
    , ('New England', 'Patriots', 'NE')
    , ('New York', 'Jets', 'NYJ')
    , ('Baltimore', 'Ravens', 'BAL')
    , ('Cincinnati', 'Bengals', 'CIN')
    , ('Cleveland', 'Browns', 'CLE')
    , ('Pittsburgh', 'Steelers', 'PIT')
    , ('Houston', 'Texans', 'HOU')
    , ('Indianapolis', 'Colts', 'IND')
    , ('Jacksonville', 'Jaguars', 'JAX')
    , ('Tennessee', 'Titans', 'TEN')
    , ('Denver', 'Broncos', 'DEN')
    , ('Kansas City', 'Chiefs', 'KC')
    , ('Los Angeles', 'Chargers', 'LAC')
    , ('Oakland', 'Raiders', 'OAK')
    , ('Dallas', 'Cowboys', 'DAL')
    , ('New York', 'Giants', 'NYG')
    , ('Philadelphia', 'Eagles', 'PHI')
    , ('Washington', 'Redskins', 'WAS')
    , ('Chicago', 'Bears', 'CHI')
    , ('Detroit', 'Lions', 'DET')
    , ('Green Bay', 'Packers', 'GB')
    , ('Minnesota', 'Vikings', 'MIN')
    , ('Atlanta', 'Falcons', 'ATL')
    , ('Carolina', 'Panthers', 'CAR')
    , ('New Orleans', 'Saints', 'NO')
    , ('Tampa Bay', 'Buccaneers', 'TB')
    , ('Arizona', 'Cardinals', 'ARI')
    , ('Los Angeles', 'Rams', 'LAR')
    , ('San Francisco', '49ers', 'SF')
    , ('Seattle', 'Seahawks', 'SEA')

   
