INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Patrick', 'Mahomes', 'Quarterback', 'QB', 'Texas Tech', 2017, '19950917')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Keenan', 'Allen', 'Wide Receiver', 'WR', 'California', 2013, '19920427')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Curtis', 'Samuel', 'Wide Receiver', 'WR', 'Ohio State', 2017, '19960811')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Josh', 'Adams', 'Running Back', 'RB', 'Notre Dame', 2018, '19961029')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Darren', 'Sproles', 'Running Back', 'RB', 'Kansas State', 2005, '19830620')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Zach', 'Ertz', 'Tight End', 'TE', 'Stanford', 2013, '19901110')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Eric', 'Ebron', 'Tight End', 'TE','North Carolina', 2014, '19930410')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Anthony', 'Miller', 'Wide Receiver', 'WR', 'Memphis', 2018, '19941009')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Melvin', 'Gordon', 'Running Back', 'RB', 'Wisconsin', 2015, '19930413')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Deshaun', 'Watson', 'Quarterback', 'QB', 'Clemson', 2017, '19950914')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Adam', 'Humphries', 'Wide Receiver', 'WR', 'Clemson', 2015, '19930624')
INSERT INTO dbo.Player (Firstname, LastName, Position, PositionAbv, College, FirstYearInLeague, Birthdate)
VALUES  ('Kareem', 'Hunt', 'Running Back', 'RB', 'Toledo', 2017, '19950806')